repos:
  - repo: https://github.com/fastai/nbdev
    rev: 2.2.10
    hooks:
    - id: nbdev_export
    - id: nbdev_clean
      files: ^nbs/.*\.ipynb|^nbs_pipeline/.*\.ipynb$

  - repo: local
    hooks:
      - id: clean-jupyter-files
        name: Clean jupyter notebooks
        entry: ./clean-jupyter-files.sh
        language: script
        files: ^nbs/.*\.ipynb|^nbs_pipeline/.*\.ipynb$
        always_run: true