include: !include "base.yaml"
#########################################################
########### NBS - PIPELINE CONFIGURATION FILE ###########
########### 02a - ENCODER ORELM               ###########
#########################################################
###### Author: Maria Inmaculada Santamaria-Valenzuela   #
###### Date: 09-2023                                    #
#########################################################

#########################
# 02c - ENCODER ORELM   #
#########################

configuration:
  job_type: 'encoder_ORELM'
  alias: *alias
  wandb:
    use: *use_wandb
    entity: *wdb_user
    group: null
    project: *wdb_project
  artifacts:
    # complete training artifact path
    train: !join [ *wdb_user, '/', *wdb_project, '/', *fname, ':v', *wdb_version]
    # complete name (None for random validation set)
    valid:
      data: null
      # In case valid_artifact is None, this will set the percentage of random items to go to val
      size: 0.1
  specifications:
    algorithm: 'OSELM'
    n_epoch: 200
    random_seed: 6
    numHiddenNeurons: 25
    activationFunction: 'sig'
    LN: true
    AE: true
    ORTH: true
    lamb: 0.0001
    weight_forgetting_factors:
      input: 1
      output: 0.92
    sliding_windows:
      # n datapoints the window is moved ahead along the sequence in the sliding window
      stride: 1
      # window size for the sliding window (taxi=48, steamflow=640)
      size: 200 #2500 #Forzando 1 ventana solo #200 #w
    
    

